theme: jekyll-theme-minimal
title: Avinash Kaul
tagline: Avinash Kaul | Technologist, Leader and Enterprise Solutions Architect
description: Technologist, Leader and Enterprise Solutions Architect
logo: /assets/img/logo.png
